name:                liquidhs
version:             0.1.0.0
github:              "ignacy/liquidhs"
license:             BSD3
author:              "Ignacy Moryc"
copyright:           "2019 Ignacy Moryc"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/liquidhs#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 7 && < 8
- hspec
- hspec-megaparsec
- text
- parser-combinators
- snap-core
- snap-server

library:
  source-dirs: src

executables:
  liquidhs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - liquidhs

tests:
  liquidhs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - liquidhs
